import type { Metadata } from "next";

import "./globals.css";
import {Rufina} from "next/font/google";
import Navbar from "@/components/Navbar";
import React from "react";

const rufina = Rufina({
    weight: ['400','700','900'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Electricians Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`rufina.className`}
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}
